version: '3.8'

services:
  database:
    image: postgres:16
    container_name: expense-db-global
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MinhHieu2816@
      - POSTGRES_DB=postgres
    volumes:
      - expense_data-global:/var/lib/postgresql/data
    restart: always

# declare volume for Docker understand this is old volume that has been created
volumes:
  expense_data-global: